place = 'New York City'
print(place.startswith('N'))
print(place.startswith('n'))
print(place.endswith('y'))
print(place.endswith('City'))
print(place.count('y'))
lower_place = place.lower()
print(lower_place)
upper_place = place.upper()
print(upper_place)
print(upper_place.count('Y'))
print(lower_place == upper_place)
print(place == upper_place)
print(place.find('C'))
print(upper_place.find('Y'))
print(place.find('York'))
print(place.index('Y'))
print(place.find('c'))
split_place = place.split('k')
print(split_place)
split_place = place.split(' ')
print(split_place)
join_char = ','
join_char.join(split_place)
print(join_char)
join_char = ' '
join_char.join(split_place)
print(join_char)
"|".join(split_place)
print(split_place)